version: "3.3"
services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
  redis:
    image: redis

  rabbitmq:
    image: rabbitmq
    ports:
      - "5671:5671"

  celery:
    build:
      context: .
    command: celery -A my_reader worker -l INFO
    volumes:
      - .:/app
    depends_on:
      - redis
      - rabbitmq
      - web
